# Generated by Django 3.1.3 on 2020-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knup', '0003_remove_fileupload_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AlterField(
            model_name='file',
            name='storedname',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
